server:
  port: 8004
spring:
  application:
    name: spring-cloud-eureka-consumer-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
feign:
  hystrix:
    #开启feign
    enabled: true
