server:
  port: 8081
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery: #如果不想将Nacos作为服务注册与发现，之间将spring.cloud.nacos.discovery 设置为 false即可
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
